### PR TITLE
Reduce the height of the m-e element because the Chromium logo doesn'…

### PR DESCRIPTION
**Pull request by aawc**
…t appear with Chromium. This was being drawn over the file path links which made it hard to click them.

### CODE REVIEW

**Comment by kalman** [comment]
Is there a way to fix up the commit message to make it git style? I.e. first line summary "Reduce the height of the m-e element." or similar, empty line, then the rest of what you've written?

The changes lgtm but the description will look a bit out of place in the commit log.

**Comment by kalman** [comment]
Also please change the version in manifest.json to 10.4.

**Comment by aawc** [comment]
Done. I am not sure if you see the changes, though.

**Comment by kalman** [comment]
I see the changes, sort of, as another patch. Lastly, could you squash these into a single commit? There are a few guides I found like http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request for how to do that.

**Comment by aawc** [comment]
OK, I tried that and it did merge them as you can see here: https://github.com/aawc/kalman-chrome-extensions/commit/eea168d2086c29de1e92db87f6ce344cff00d0bd

I am not sure we are in a much better state now than earlier since it has linked even more commits to the PR now.

**Comment by kalman** [comment]
I'm still trying to figure out what is going on here. This interface is super confusing.

**Comment by kalman** [comment]
Couple more things though.
1. Like my other commits, put "OmniChromium: " before the summary (sorry for missing this out).
2. You've lost the structure I mentioned earlier, with summary followed by blank line followed by message.

**Comment by kalman** [comment]
I tried the squash myself and these instructions worked: http://push.cwcon.org/learn/squashing-commits.html

**Comment by aawc** [comment]
I am sorry I closed this PR without checking with you first but I had ended up spending too much time trying to wrestle Git. I have opened PR https://github.com/kalman/chrome-extensions/pull/5 for the exact same change following the guidelines you outlined in this PR. Sorry again and thanks for reviewing the change.

**Pull request closed without merging**
